// <auto-generated />
using Dwk.Api.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace Dwk.Api.Migrations
{
    [DbContext(typeof(DwkApiContext))]
    [Migration("20180525020232_secondMigration")]
    partial class secondMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026");

            modelBuilder.Entity("Dwk.Api.Models.Attribute", b =>
                {
                    b.Property<string>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("DeseaseId");

                    b.Property<string>("content");

                    b.Property<string>("name");

                    b.HasKey("ID");

                    b.HasIndex("DeseaseId");

                    b.ToTable("Attribute");
                });

            modelBuilder.Entity("Dwk.Api.Models.Desease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("abstract");

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("Deseases");
                });

            modelBuilder.Entity("Dwk.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Dwk.Api.Models.Attribute", b =>
                {
                    b.HasOne("Dwk.Api.Models.Desease")
                        .WithMany("attributes")
                        .HasForeignKey("DeseaseId");
                });
#pragma warning restore 612, 618
        }
    }
}
